### ISSUE TITLE
Allow to use the enclosure tag

### ISSUE THREAD

**Issue by meza** [lwojcik/github-action-feed-to-social-media#14]
Hey,

This is almost perfect for my usecase however I'm really missing the `enclosure` field as that's what's important for the podcast atom feeds. Honestly, the best thing would probably be to pull in all tags and let us use whatever's there.

For example the `<itunes:episode>` is another important one.

If you want to inspect a podcast feed, check this out: https://podcast.themezaofficial.com/feed

**Comment by lwojcik** [comment]
Hey @meza, thanks for reaching out! I'll see what can be done.

**Comment by meza** [comment]
You might be better off with a raw [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser) instead of `@extractus/feed-extractor`.

The latter feels like it's trying to make arbitrary decisions for you by default (like the max description length :/)

**Comment by lwojcik** [comment]
> You might be better off with a raw [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser) instead of `@extractus/feed-extractor`.

That's a good idea. The argument for `@extractus/feed-extractor` was that it supports RSS and [JSON feeds](https://www.jsonfeed.org/) but if anyone expresses interest in JSON feed support it won't be complicated to provide two different drivers for different file types.

Hang tight, I'll be exploring that in the upcoming week.

**Comment by lwojcik** [comment]
I have a wider list of supported tags ready to release, it will land in `v2.1.0`.

Boring tech stuff:

- `@extractus/feed-extractor` is there to stay. I use Atom feeds in my projects, so with `fast-xml-parser` I'd have had to reimplement my own parsers for both formats - too much work, and the library is actually pretty darn good at what it does
- `description` property is truncated at 999999 characters (no way to turn it off entirely for now)
- with the way `@extractus/feed-extractor` currently works I can't easily offer support for _all_ properties. But I made it possible to add new ones if anyone asks. I talked to the author of the library and if they proceed with changes I requested I might at some point add support for all properties, known and unknown.

Please try `v2.1.0` out once it lands and let me know if that helps!

**Comment by meza** [comment]
Great stuff! I'll check it out soon, I'm on my own adventure with a project 😓
