### ISSUE TITLE
Feature: new post formatting - {excerpt}

### ISSUE THREAD

**Issue by tedleyem** [lwojcik/github-action-feed-to-social-media#48]
I use Jekyll for blogging via Github Pages. Using a common Minima theme, the [display of excepts is controlled by the site.show_excerpts variable](https://github.com/jekyll/minima#enabling-excerpts-on-the-home-page). 

I use the "excerpt" tag as a tagline and would love to have that added as a parameter so that I can have my Post format look like this 

 mastodonPostFormat: "New post: {title} - {excerpt}\n\n{link}"

Is this the proper way to suggest this "issue" 
I can put in the work and submit a PR if this aligns with the project.

**Comment by lwojcik** [comment]
Hi @tedleyem! Thanks for raising this.

I'll be looking at this within next few days, but a PR is certainly welcome.
